device/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("data", views.insert_log),
    path("device/<str:serial_no>", views.device_chart, name="device"),
    path("alarms", views.AddAlarm.as_view(), name="alarms"),
    path("setting/<str:serial_no>", views.Setting.as_view(), name="setting"),
    path("add-device", views.AddDevice.as_view(), name="add-device"),
    path("date-range", views.date_range, name="date-range"),
    path("device-detail/<str:serial_no>", views.device_detail, name="device-detail"),
    path("devices", views.MyDevices.as_view(), name="devices"),
]

eco_monitor/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("dashboard.urls")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("accounts/", include("accounts.urls")),
    path("device/", include("device.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

device/models.py
from django.db import models
from django.contrib.auth.models import User


class Type(models.Model):
    type = models.CharField(max_length=50)

    def __str__(self):
        return self.type


class Device(models.Model):
    name = models.CharField(max_length=100)
    serial_no = models.CharField(max_length=6, unique=True)
    owner = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, related_name="devices")
    dehumidifier = models.BooleanField()
    humidifier = models.BooleanField()
    cooler = models.BooleanField()
    heater = models.BooleanField()
    max_temperature = models.IntegerField(default=40)
    min_temperature = models.IntegerField(default=10)
    max_humidity = models.IntegerField(default=50)
    min_humidity = models.IntegerField(default=30)

    def __str__(self):
        return self.name


class AlarmType(models.Model):
    type = models.CharField(max_length=50)
    description = models.TextField()

    def __str__(self):
        return self.type


class Alarms(models.Model):
    device = models.ForeignKey(Device,on_delete=models.CASCADE, null=True,related_name="alarms",verbose_name="دستگاه",)
    type = models.ForeignKey(AlarmType, on_delete=models.CASCADE, verbose_name="تایپ")
    target_id = models.CharField(max_length=50, verbose_name="ورودی")
    is_active = models.BooleanField(default=True)
    is_triggered = models.BooleanField(default=False)
    target = models.FloatField(null=True, blank=True, verbose_name="مقدار (ماکسیمم)")


class Log(models.Model):
    is_seen = models.BooleanField(default=False)
    creation_datetime = models.DateTimeField()
    device = models.ForeignKey( Device, on_delete=models.CASCADE, null=True, related_name="logs")
    temperature = models.FloatField(null=True, blank=True)
    humidity = models.FloatField(null=True, blank=True)
    dehumidifier = models.BooleanField(null=True, blank=True)
    humidifier = models.BooleanField(null=True, blank=True)
    cooler = models.BooleanField(null=True, blank=True)
    heater = models.BooleanField(null=True, blank=True)

device/forms.py
from django import forms
from .models import Alarms


class AddDeviceForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "نام دلخواه خود را وارد کنید."}),
        max_length=50,
        label="نام دستگاه"
    )
    serial_no = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "شماره سریال نوشته شده روی دستگاه را وارد کنید."}),
        max_length=10,
        label="شماره سریال"
    )
    min_temperature = forms.IntegerField(required=False, label="حداقل دما", widget=forms.TextInput(
        attrs={"placeholder": " درصورت کمتر شدن دمای محیط از این مقدار، دستگاه هیتر روشن میشود. (مقدار دیفالت ۱۰)"}))
    max_temperature = forms.IntegerField(required=False, label="حداکثر دما", widget=forms.TextInput(
        attrs={"placeholder": " درصورت بیشتر شدن دمای محیط از این مقدار، دستگاه کولر روشن میشود. (مقدار دیفالت ۴۰)"}))
    min_humidity = forms.IntegerField(required=False, label=" حداقل رطوبت", widget=forms.TextInput(
        attrs={"placeholder": " درصورت کمتر شدن رطوبت محیط از این مقدار، دستگاه رطوبت ساز روشن میشود. (مقدار دیفالت ۳۰)"}),)
    max_humidity = forms.IntegerField(required=False, label="حداکثر رطوبت", widget=forms.TextInput(
        attrs={"placeholder": " درصورت بیشتر شدن رطوبت محیط از این مقدار، دستگاه رطوبت گیر روشن میشود. (مقدار دیفالت ۵۰)"}))


class SettingForm(forms.Form):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={"placeholder": "نام دلخواه خود را وارد کنید."}),
        max_length=50,
        label="نام دستگاه"
    )
    min_temperature = forms.IntegerField(required=False, label="حداقل دما", widget=forms.TextInput(
        attrs={"placeholder": " درصورت کمتر شدن دمای محیط از این مقدار، دستگاه هیتر روشن میشود. (مقدار دیفالت ۱۰)"}))
    max_temperature = forms.IntegerField(required=False, label="حداکثر دما", widget=forms.TextInput(
        attrs={"placeholder": " درصورت بیشتر شدن دمای محیط از این مقدار، دستگاه کولر روشن میشود. (مقدار دیفالت ۴۰)"}))
    min_humidity = forms.IntegerField(required=False, label=" حداقل رطوبت", widget=forms.TextInput(
        attrs={"placeholder": " درصورت کمتر شدن رطوبت محیط از این مقدار، دستگاه رطوبت ساز روشن میشود. (مقدار دیفالت ۳۰)"}),)
    max_humidity = forms.IntegerField(required=False, label="حداکثر رطوبت", widget=forms.TextInput(
        attrs={"placeholder": " درصورت بیشتر شدن رطوبت محیط از این مقدار، دستگاه رطوبت گیر روشن میشود. (مقدار دیفالت ۵۰)"}))
    dehumidifier = forms.BooleanField(label='رطوبت گیر', required=False)
    humidifier = forms.BooleanField(label='رطوبت ساز', required=False)
    cooler = forms.BooleanField(label='کولر', required=False)
    heater = forms.BooleanField(label='هیتر', required=False)


class AlarmForm(forms.ModelForm):
    class Meta:
        model = Alarms
        fields = ["device", "type", "target_id", "target"]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super(AlarmForm, self).__init__(*args, **kwargs)
        self.fields["device"].queryset = user.devices.all()
        # self.fields['target_id'].required = False

device/views.py
import datetime
from django.contrib.auth import authenticate
from django.views.generic.base import TemplateView
from django.http import HttpResponse, JsonResponse
from django.views.generic import ListView, DetailView
from django.views.generic.edit import FormView, CreateView
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from persiantools.jdatetime import JalaliDateTime, JalaliDate
from .models import *
from .forms import *
from persiantools import characters, digits

import pytz

def device_detail(request, serial_no):
    # logs = []
    device = Device.objects.get(serial_no=serial_no)
    # device_logs = Log.objects.filter(device=device).order_by("-creation_datetime")
    # for log in device_logs:
    #     sensors = dict()
    #     sensors["date"] = JalaliDate(log.creation_datetime.date())
    #     sensors["time"] = log.creation_datetime.astimezone()
    #     if log.analog_input_1 == None:
    #         sensors["a1"] = "-"
    #     else:
    #         sensors["a1"] = log.analog_input_1

    #     if log.analog_input_2 == None:
    #         sensors["a2"] = "-"
    #     else:
    #         sensors["a2"] = log.analog_input_2

    #     if log.analog_input_3 == None:
    #         sensors["a3"] = "-"
    #     else:
    #         sensors["a3"] = log.analog_input_3

    #     if log.analog_input_4 == None:
    #         sensors["a4"] = "-"
    #     else:
    #         sensors["a4"] = log.analog_input_4
    #     sensors["d1"] = log.digital_input_1
    #     sensors["d2"] = log.digital_input_2
    #     sensors["d3"] = log.digital_input_3
    #     sensors["d4"] = log.digital_input_4
    #     sensors["d5"] = log.digital_input_5
    #     sensors["d6"] = log.digital_input_6
    #     logs.append(sensors)
    # # paginator = Paginator(sensors, 25)  # Show 25 contacts per page.
    # chartLogs = chart_logs(device)
    # tLogs = chartLogs[len(chartLogs) - 1]
    devices = []
    myDevices = Device.objects.filter(owner=request.user)

    # tables = dataTable(myDevices)
    charts = chartsData(myDevices)
    return render(
        request,
        "device/device_detail.html",
        {"device": device,  "chartLogs": charts},
    )




def chart_logs(device, td=datetime.datetime.today(), days=30):
    chartLogs = []
    for d in (
        td - datetime.timedelta(days=x) for x in range(0, days)
    ):
        date =d.date() # datetime.date(day=d.day, year=d.year, month=d.month)
        dayLogs =Log.objects.filter(device=device,creation_datetime__year =date.year, creation_datetime__month = date.month , creation_datetime__day = date.day) # Log.objects.filter(creation_datetime.date=date)
        if len(dayLogs) > 0:
            dLogs = dict()
            dLogs["date"] = JalaliDate(date).strftime('%Y/%m/%d')
            on = [0, 0, 0, 0, 0, 0]
            for y in reversed(range(0, len(dayLogs) - 1, 1)):
                time1 = dayLogs[y + 1].creation_datetime
                time2 = dayLogs[y].creation_datetime
                time = int((time1 - time2).total_seconds() / 60)
                if dayLogs[y].digital_input_1:
                    on[0] += time
                if dayLogs[y].digital_input_2:
                    on[1] += time
                if dayLogs[y].digital_input_3:
                    on[2] += time
                if dayLogs[y].digital_input_4:
                    on[3] += time
                if dayLogs[y].digital_input_5:
                    on[4] += time
                if dayLogs[y].digital_input_6:
                    on[5] += time

            dLogs["on"] = on
            chartLogs.insert(0, dLogs)
    return(chartLogs)

def date_range(request):
    serial_no=request.POST.get('device')
    device = Device.objects.get(serial_no=serial_no)

    from_date = request.POST.get('fd').split('/')
    to_date = request.POST.get('td').split('/')
    fd = JalaliDateTime(int(from_date[0]), int(from_date[1]), int(from_date[2]))
    td = JalaliDateTime(int(to_date[0]), int(to_date[1]), int(to_date[2]))
    days=(td.date()-fd.date()).days+1
    chartLogs = chart_logs(device,td,days)
    return JsonResponse({"chartLogs": chartLogs}, status=200)

@login_required(login_url="login")
def device_chart(request,serial_no):
    devices = []
    device = Device.objects.get(serial_no=serial_no)
    devices.append(device)
    if request.method == "GET":
        # data = chart_logs(device)
        # devices = []
        charts = chartsData(devices)
        context = {
            "charts": charts,
            "serial_no":serial_no
            }
        return render(request, "device/device.html", context)    
    else:
        try:
            from_date = request.POST.get('fd').split('/')
            to_date = request.POST.get('td').split('/')
            fd = JalaliDate(int(from_date[0]), int(
                from_date[1]), int(from_date[2])).to_gregorian()

            td = JalaliDate(int(to_date[0]), int(
                to_date[1]), int(to_date[2])).to_gregorian()
            if td > fd:
                print(request.POST.get('fd'))
                print(devices)
                chartLogs = chartsData(devices,fd,td)
                print(chart_logs)
                context = {
                    "chartLogs": chartLogs,
                    "serial_no": serial_no
                }
                return JsonResponse(context, status=200)
        except:
            context = {
                "message": "بازه زمانی انتخابی شما اشتباه می‌باشد! لطفا در انتخاب بازه زمانی دقت کنید."
                , "serial_no": serial_no
            }

        return render(request, "device/device.html", context)


def chartsData(devices, sd=False, fd=False):
    
    colors = ['#e76c90', '#FFB6C1', '#dde1e9', "#708090", "#8A2BE2", "#800080"]
    data = []
    td = datetime.datetime.today()
    d = td - datetime.timedelta(days=7)
    x = 0
    if sd == False:
        print('ji')
        logs = devices[0].logs.all().order_by("creation_datetime")
    else:
        print(sd)
        logs = devices[0].logs.filter(creation_datetime__range=[sd, fd])
        print(logs)
    for idx, device in enumerate(devices):
        deviceData = dict()
        deviceTemperature = []
        deviceHumidity = []
        deviceLabel = []
        for log in logs:
            x = x+1
            deviceTemperature.append(log.temperature)
            deviceHumidity.append(log.humidity)
            iran_timezone = pytz.timezone('Asia/Tehran')
            time = log.creation_datetime.astimezone(
                iran_timezone).strftime('%H:%M:%S')
            date = JalaliDate(log.creation_datetime).strftime('%Y/%m/%d')
            deviceLabel.append(time+' '+date)
        deviceData['name'] = device.name
        deviceData['color'] = colors[idx]
        deviceData['temperature'] = deviceTemperature
        deviceData['humidity'] = deviceHumidity
        deviceData['label'] = deviceLabel
        data.append(deviceData)
    return data

class MyDevices(ListView):
    template_name = "device/devices.html"
    context_object_name = "devices"
    model = Device

    def get_queryset(self):
        queryset = Device.objects.filter(owner=self.request.user)
        return queryset

class DeviceDetail(DetailView):
    template_name = "products/product.html"
    model = Device

class myDevice(TemplateView):
    template_name = "device/device.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        serial_no = kwargs['serial_no']
        device = self.request.user.devices.get(serial_no=serial_no)
        print(device)
        data = chart_logs(device)
        context["device"] = device.serial_no
        context["chartLogs"] = data
        return context

class Setting(FormView):
    form_class = SettingForm
    template_name = "device/setting.html"
    success_url = "/device/devices"

    def get_initial(self):
        serial_no = self.kwargs["serial_no"]
        initial = super(Setting, self).get_initial()
        device = Device.objects.get(serial_no=serial_no)
        initial.update(
            {
                "name": device.name,
                "min_temperature": device.min_temperature,
                "max_temperature": device.max_temperature,
                "min_humidity": device.min_humidity,
                "max_humidity": device.max_humidity,
                "dehumidifier": device.dehumidifier,
                "humidifier": device.humidifier,
                "cooler": device.cooler,
                "heater": device.heater,
            }
        )
        return initial

    def form_valid(self, form):
        if form.has_changed():
            data = form.cleaned_data
            serial_no = self.kwargs["serial_no"]
            device = Device.objects.get(serial_no=serial_no)
            device.name = data["name"]
            device.min_temperature = data["min_temperature"]
            device.max_temperature = data["max_temperature"]
            device.min_humidity = data["min_humidity"]
            device.max_humidity = data["max_humidity"]
            device.dehumidifier = data["dehumidifier"]
            device.humidifier = data["humidifier"]
            device.cooler = data["cooler"]
            device.heater = data["heater"]
            device.save()
        return super().form_valid(form)

class AddDevice(FormView):
    form_class = AddDeviceForm
    template_name = "device/add_device.html"
    success_url = "/device/devices"

    def form_valid(self, form):
        serial_no = form.cleaned_data["serial_no"]
        if serial_no == "":
            form.add_error("serial_no", "شماره سریال را وارد کنید.")
        serial_no = f'{digits.fa_to_en(serial_no)}'
        if Device.objects.filter(serial_no=serial_no).exists():
            device = Device.objects.get(serial_no=serial_no)
            if device.owner.is_superuser:
                form.clean()
                device.owner = self.request.user 
                if form.cleaned_data["name"] != '':

device/templates/device/add_device.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block page_header %}افزودن دستگاه{% endblock page_header %}
{% block content %}
    <div class="col-md-12 col-xl-12 col-xs-12 col-sm-12">
        <div class="widget has-shadow">
            <div class="widget-body p-3 row">
        <div class="px-5 py-3 m-4">
            {% comment %} <h4 class="main-content-label">افزودن دستگاه</h4> {% endcomment %}
            <h4 class='pt-3'>اطلاعات دستگاه را وارد کنید.</h4>
            {% for key, val in form.errors.items %}
                <div class="alert alert-danger alert-dissmissible fade show mt-4" role="alert">
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close"></button>
                    <strong>خطا!</strong> {{val}}
                </div>
            {% endfor %}

            <form method="POST" class='row  pr-0' >
                {% csrf_token %}
                {% for field in form %} 
                    <div class="form-group col-md-12 col-xl-6 col-xs-12 col-sm-12 p-3 py-4 m-0">
                        <p>{{field.label}}</p>
                        {{ field|add_class:'form-control'}}
                    </div>
                {% endfor %}
                {% comment %} <div class='text-center col-6 pt-3'> {% endcomment %}
                <div class=' col-12  text-center py-4' >
                    <button class=' btn btn-primary px-5'>تایید</button>
                </div>
           
            </form>
        </div>
        </div>
        </div>
    </div>
{%endblock%}

device/templates/device/alarm.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block page_header %} آلارم ها{% endblock page_header %}
{% block content %}
    <div class="col-md-12 col-xl-12 col-xs-12 col-sm-12">
        <div class="widget has-shadow">
            <div class="widget-body p-3 ">
                <div class="m-4 row">
                    <h4 class="main-content-label"></h4>
                    <p class='pt-3'></p>
                    {% if alarms %}
                    <table class=" col-12 table mt-5 text-center">
                        <thead>
                            <tr>
                                <th>نام دستگاه</th>
                                <th>ورودی</th>
                                <th>مقدار</th>
                                <th>وضعیت فعال بودن</th>
                                <th></th>
                                {% comment %} <th></th> {% endcomment %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for item in alarms %}
                                <tr>
                                    <td>{{item.device}}</td>
                                    <td>ورودی {{item.type}} {{item.target_id}}</td>
                                    <td>{{item.target}}</td>
                                    <td><div class='d-flex justify-content-center'>{% if item.is_active %}<span class="badge-pulse-green"></span>{% else %}<span class="badge-pulse"></span>{% endif %}</div></td>
                                    <td><div class="c-icon" onclick="location.href='{% url "alarms" %}'"><i class="la la-cog"></i></div></td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                    {% endif %}
                </div>
                <div class='col-12 text-center pb-5'>
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modal-centered">تنظیم آلارم جدید</button>
                </div>
            </div>
        </div>
    </div>
    <div id="modal-centered" class="modal fade show" style="display: none;">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">تنظیم آلارم</h4>
                    <button type="button" class="close" data-dismiss="modal">
                        <span aria-hidden="true">×</span>
                        <span class="sr-only">بستن</span>
                    </button>
                </div>
                <div class="modal-body px-5">
                    <form id='add_alarm' method="POST" class='row pr-0' >
                        {% csrf_token %}
                        {{form.errors}}
                        {% for field in form %} 
                            <div class="form-group col-12 p-2 m-0">
                                <p id='{{field.name}}'>{{field.label}}</p>
                            {% if field.name == 'target_id' %}
                            <select name='target_id' class="form-control " required="" id="id_target_id">
                                <option value="" selected="">---------</option>
                                <option value="1"> ورودی 1</option>
                                <option value="2"> ورودی 2</option>
                                <option value="3"> ورودی 3</option>
                                <option value="4"> ورودی 4</option>
                            </select>
                            {% else %}
                                {{ field|add_class:'form-control '}}
                                {% if field.errors %}
                                    <p class="alert alert-danger alert-dismissible fade show mb-0">{{ field.errors|striptags}}</p> 
                                {% endif %}
                            {% endif %}
                            </div>
                        {% endfor %}
                        <div class='col-12 text-center pt-3'>
                            <button type='submit' onClick='test()' class=' btn btn-primary px-5'>تایید</button>
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-shadow" data-dismiss="modal">بستن</button>
                </div>
            </div>
        </div>
    </div>
{%endblock%}

{% block scripts %}
<script>
    $(document).ready(function () {
        $("#id_type").change(function () {
            var val = $(this).val();
                if (val == '1') {
                    $('#target').text('مقدار (ماکسیمم)')
                    $("#id_target_id").html(`
                    <option value="" selected="">---------</option>
                    <option value="1"> ورودی 1</option>
                    <option value="2"> ورودی 2</option>
                    <option value="3"> ورودی 3</option>
                    <option value="4"> ورودی 4</option>
                `)
                    }
                else{
                    console.log('.-.')
                    $('#target').text('مقدار (دقیقه)')
                    $("#id_target_id").html(`
                    <option value="" selected="">---------</option>
                    <option value="1"> ورودی 1</option>
                    <option value="2"> ورودی 2</option>
                    <option value="3"> ورودی 3</option>
                    <option value="4"> ورودی 4</option>
                    <option value="5"> ورودی 5</option>
                    <option value="6"> ورودی 6</option>
                `)
                }

            
        });
    });
</script>
{% endblock scripts %}

device/templates/device/devices.html
{% extends 'base.html' %} {% load static %} 
{% block page_header %} دستگاه ها{% endblock page_header %}
{% block content %}
<div class="col-md-12 col-xl-12 col-xs-12 col-sm-12">
    <div class="widget has-shadow">
        <div class="widget-body p-5 ">
            {% if devices %}
            <table class=" table text-center">
                <thead>
                    <tr>   
                        <th>نام دستگاه</th>
                        <th>شماره سریال</th>
                        <th>هیتر</th>
                        <th>کولر</th>
                        <th>رطوبت ساز</th>
                        <th>رطوبت گیر</th>
                        <th></th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in devices %}
                        <tr>
                            <td>{{item.name}}</td>
                            <td>{{item.serial_no}}</td>
                            <td>{% if item.heater %} <span class="badge-text badge-text-small success">روشن</span> {% else %}<span class="badge-text badge-text-small danger">خاموش</span>{% endif %}</td>
                            <td>{% if item.cooler %} <span class="badge-text badge-text-small success">روشن</span> {% else %}<span class="badge-text badge-text-small danger">خاموش</span>{% endif %}</td>
                            <td>{% if item.humidifier %} <span class="badge-text badge-text-small success">روشن</span> {% else %}<span class="badge-text badge-text-small danger">خاموش</span>{% endif %}</td>
                            <td>{% if item.dehumidifier %} <span class="badge-text badge-text-small success">روشن</span> {% else %}<span class="badge-text badge-text-small danger">خاموش</span>{% endif %}</td>
                            <td class='text-center'><button class="btn btn-primary" onclick="location.href='{% url "device" item.serial_no %}'">مشاهده</button></td>
                            <td><div class="c-icon" onclick="location.href='{% url "setting" item.serial_no %}'"><i class="la la-cog"></i></div></td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="main-error-wrapper  m-4  text-center">
                <h5>دستگاهی موجود نیست!</h5>
                <a class="btn btn-outline-danger mt-3" href={% url 'add-device' %} >افزودن دستگاه</a>
            </div>
        {% endif %}
    </div>
    </div>
    </div>
{%endblock%}

device/templates/device/setting.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block page_header %}تنظیمات دستگاه{% endblock page_header %}

{% block content %}
    <div class="">
        <div class="widget has-shadow">
            <div class="widget-body p-5 row">
            {% comment %} <h4 class="main-content-label pb-2">تنظیمات دستگاه</h4> {% endcomment %}
            <form method="POST" class=' row' >
                {% csrf_token %}
                {% for field in form %} 
                    
                    {% if  field.name == "name" %}
                    <div class=" p-3 m-0 col-12 px-3">
                        <div class='col-2 pt-3 pl-2'>
                            {{field.label}}
                        </div>
                        <br>
                        {{ field|add_class:'form-control col-sm-12 '}}
                    {% elif  field.name == "min_temperature" %}
                    <div class=" p-3 m-0 col-6 ">
                        <div class='col-12 pt-3'>
                            {{field.label}}
                        </div>
                        <br>
                        {{ field|add_class:'form-control col-12'}}
                    {% elif  field.name == "max_temperature" %}
                    <div class=" p-3 m-0 col-6 ">
                        <div class='col-12 pt-3'>
                            {{field.label}}
                        </div>
                        <br>
                        {{ field|add_class:'form-control col-12'}}
                    {% elif  field.name == "min_humidity" %}
                    <div class=" p-3 m-0 col-6 ">
                        <div class='col-12 pt-3'>
                            {{field.label}}
                        </div>
                        <br>
                        {{ field|add_class:'form-control col-12'}}
                    {% elif  field.name == "max_humidity" %}
                    <div class=" p-3 m-0 col-6 ">
                        <div class='col-12 pt-3'>
                            {{field.label}}
                        </div>
                        <br>
                        {{ field|add_class:'form-control col-12'}}
                    {% else %}   
                    <div class=" p-3 m-0 col-6 row">
                        <div class='col-3 pt-3'>
                            {{field.label}}
                        </div>   
                        <br>                 
                        {{field|add_class:''}}
                        {% endif %}
                            {% if field.errors %}
                                <p class="alert alert-danger alert-dismissible fade show mb-0">{{ field.errors|striptags}}</p> 
                            {% endif %}
                        </div>
                {% endfor %}
                {% comment %} <div class='text-center col-6 pt-3'> {% endcomment %}
                <div class='col-12 pt-5 text-center'>
                    <button class=' btn btn-primary px-5'>تایید</button>
                </div>
            </form>
        </div>
        </div>
        </div>
    </div>
{%endblock%}